# build config
builds:
  - env:
      - CGO_ENABLED=0
    id: "gptcomet"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    binary: "gptcomet"
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

# archives config
archives:
  - format: tar.gz
    # use zip for windows
    format_overrides:
      - goos: windows
        format: zip
    name_template: "gptcomet_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README*
      - LICENSE*

# checksum config
checksum:
  name_template: 'checksums.txt'

# snapshot config
snapshot:
  name_template: "{{ incpatch .Version }}-next"

# changelog config
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request 