# build config
version: 2

before:
  hooks:
    - go mod tidy

builds:
  # Linux/Windows - 使用UPX压缩
  - id: "gptcomet-upx"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    binary: "gptcomet"
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath
    hooks:
      post:
        - upx --best --lzma "{{ .Path }}"

  # macOS - 不使用UPX (不支持)
  - id: "gptcomet-darwin"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    binary: "gptcomet"
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

# archives config
archives:
  - id: upx-archives
    builds:
      - gptcomet-upx
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "gptcomet_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README*
      - LICENSE*

  - id: darwin-archives
    builds:
      - gptcomet-darwin
    format: tar.gz
    name_template: "gptcomet_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README*
      - LICENSE*

# checksum config
checksum:
  name_template: 'checksums.txt'

# snapshot config
snapshot:
  version_template: "{{ incpatch .Version }}-next"

# changelog config
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
