package errors

const (
	// Error Titles
	ErrTitleConfigNotFound      = "Configuration File Not Found"
	ErrTitleAPIKeyNotSet        = "API Key Not Configured"
	ErrTitleNoStagedChanges     = "No Staged Changes Found"
	ErrTitleNetworkConnection   = "Network Connection Failed"
	ErrTitleAPIRequest          = "API Request Failed"
	ErrTitleAPIAuth             = "API Authentication Failed"
	ErrTitleInvalidConfig       = "Invalid Configuration Value"
	ErrTitleNotGitRepo          = "Not a Git Repository"
	ErrTitleGitCommand          = "Git Command Failed"
	ErrTitleModelNotFound       = "Model Not Found"
	ErrTitleProviderCreation    = "Provider Creation Failed"
	ErrTitleVCSCreation         = "VCS Creation Failed"
	ErrTitleProxyConfiguration  = "Proxy Configuration Error"
	ErrTitleRequestCreation     = "Request Creation Failed"
	ErrTitleRequestExecution    = "Request Execution Failed"
	ErrTitleResponseParsing     = "Response Parsing Failed"
	ErrTitleDependencyCreation  = "Dependency Creation Failed"
	ErrTitleInternalError       = "Internal Error"
	ErrTitleRequestRetry        = "Request Failed After Retries"
	ErrTitleMessageFormatting   = "Message Formatting Failed"
	ErrTitleRequestMarshaling   = "Request Marshaling Failed"
	ErrTitleAPIStatusError      = "API Request Failed"
	ErrTitleCallbackError       = "Callback Function Failed"
	ErrTitleUnsupportedProxy    = "Unsupported Proxy Scheme"

	// Common Messages
	ErrMsgConfigNotFound      = "Cannot find configuration file at: %s"
	ErrMsgAPIKeyNotSet        = "Provider '%s' requires an API key, but none was found."
	ErrMsgNoStagedChanges     = "There are no staged changes to generate a commit message for."
	ErrMsgNetworkConnection   = "Cannot connect to API endpoint '%s'"
	ErrMsgAPIRateLimit        = "The API returned an error: %d Rate limit exceeded. Please try again later."
	ErrMsgAPIAuth             = "Authentication with provider '%s' failed. Please check your API key."
	ErrMsgInvalidConfig       = "Configuration key '%s' has an invalid value: %s"
	ErrMsgNotGitRepo          = "The current directory is not a git repository."
	ErrMsgGitCommand          = "Git command '%s' failed."
	ErrMsgModelNotFound       = "Model '%s' is not available for provider '%s'."
	ErrMsgProviderCreation    = "Failed to initialize provider '%s'."
	ErrMsgVCSCreation         = "Failed to create VCS client '%s'."
	ErrMsgProxyConfiguration  = "Failed to configure proxy settings."
	ErrMsgRequestCreation     = "Failed to create HTTP request."
	ErrMsgRequestExecution    = "Failed to execute HTTP request."
	ErrMsgResponseParsing     = "Failed to parse API response."
	ErrMsgDependencyCreation  = "Failed to create required dependencies."
	ErrMsgInternalError       = "An internal error occurred: %s"
	ErrMsgRequestRetry        = "Request failed after %d attempts."
	ErrMsgMessageFormatting   = "Failed to format message for API request."
	ErrMsgRequestMarshaling   = "Failed to serialize request payload."
	ErrMsgAPIStatusError      = "API request failed with status code %d."
	ErrMsgCallbackError       = "Callback function returned an error."
	ErrMsgUnsupportedProxy    = "Proxy scheme '%s' is not supported."

	// Common Suggestions
	SuggInitConfig            = "Run 'gptcomet config init' to create a default configuration"
	SuggCheckConfigPath       = "Run 'gptcomet config path' to see expected config location"
	SuggSetAPIKey             = "Set API key: gptcomet config set %s.api_key <your-key>"
	SuggSetEnvVar             = "Or set env var: export %s=<your-key>"
	SuggCheckProvider         = "Check provider: gptcomet config get %s"
	SuggStageFiles            = "Stage files: git add <files>"
	SuggCheckStatus           = "Check status: git status"
	SuggStageAll              = "Stage all: git add -A"
	SuggCheckInternet         = "Check internet connection"
	SuggTryCurl               = "Try: curl -I %s"
	SuggCheckProxy            = "Check proxy settings: gptcomet config get proxy"
	SuggUseProxyFlag          = "Use --proxy flag to set proxy if needed"
	SuggWaitRetry             = "Wait a few minutes and retry"
	SuggCheckQuota            = "Check your API quota and usage"
	SuggUpgradePlan           = "Consider upgrading your API plan"
	SuggUseDifferentProvider  = "Or use a different provider"
	SuggVerifyAPIKey          = "Verify API key: gptcomet config get %s.api_key"
	SuggSetNewAPIKey          = "Set new API key: gptcomet config set %s.api_key <your-key>"
	SuggCheckKeyValid         = "Check if the API key is valid and not expired"
	SuggEnsurePermissions     = "Ensure the API key has the required permissions"
	SuggCheckCurrentValue     = "Check current value: gptcomet config get %s"
	SuggSetValidValue         = "Set a valid value: gptcomet config set %s <valid-value>"
	SuggInitGit               = "Initialize a git repository: git init"
	SuggNavigateGit           = "Or navigate to a git repository"
	SuggCheckGitInstalled     = "Check if git is installed: git --version"
	SuggEnsureInGit           = "Ensure you're in a git repository"
	SuggCheckGitOutput        = "Check the git command output for more details"
	SuggCheckAvailableModels  = "Check available models for %s"
	SuggSetValidModel         = "Set a valid model: gptcomet config set %s.model <valid-model>"
	SuggVisitDocs             = "Visit provider documentation for model list"
	SuggCheckProviderConfig   = "Check provider configuration: gptcomet config list"
	SuggCheckVCSType          = "Ensure the VCS type is supported (git or svn)"
	SuggCheckProxyFormat      = "Verify proxy URL format: http://host:port or socks5://host:port"
	SuggCheckAPIEndpoint      = "Verify the API endpoint is correct"
	SuggCheckResponseFormat   = "Check if the API response format matches expectations"
	SuggReportIssue           = "If the problem persists, please report an issue on GitHub"
	SuggCheckProviderStatus   = "Check if the provider's API service is operational"
	SuggVerifyRequestPayload  = "Verify that the request payload is correctly formatted"
	SuggCheckErrorDetails     = "Check the error details for more information"
	SuggSupportedProxySchemes = "Supported proxy schemes: http, https, socks5"
)
